openfda:
  api:
    searchUrl: https://api.fda.gov/drug/drugsfda.json?search=

spring:
  datasource:
    url: jdbc:h2:mem:openfda
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
